name: Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Change this if you want a different branch to trigger the workflow

jobs:
  push_to_ecr:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Authenticate Docker with ECR
      - name: Authenticate Docker with AWS ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t resume-builder-frontend .

      # Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag resume-builder-frontend ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/resume-builder/frontend:latest

      # Push the image to ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/resume-builder/frontend:latest
